name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    name: Tests + SonarQube + Docker + ZAP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      # Step 4: Run Unit Tests with Coverage
      - name: Run Unit Tests
        run: |
          coverage run -m unittest discover -s . -p "test_*.py"
          coverage xml

      # Step 5: SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=Ashwadhani_python
            -Dsonar.organization=ashwadhani
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 6: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 7: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      # Step 8: Run Docker container on port 8000
      - name: Run Docker App
        run: |
          docker run -d -p 8000:8000 --name my-app-container my-app:latest
          sleep 10  # wait for the app to be ready

      # Step 9: Run OWASP ZAP Baseline Scan
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8000'
          rules_file_name: 'rules-ignore.txt'
          fail_on_risk: 'medium'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 10: Stop Docker Container
      - name: Stop Docker Container
        run: |
          docker stop my-app-container
          docker rm my-app-container
